# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQ8H8C8KUd6H7IQj4QeBJxnlVFvEXd6I
"""

import streamlit as st
import joblib
import pandas as pd

# Load the saved model
model = joblib.load("random_forest_model.pkl")

st.title("Subsidy Fraud Detection System")

# User inputs
amount = st.number_input("Subsidy Amount (NGN)", min_value=0, step=100)
wallet_balance = st.number_input("Wallet Balance (NGN)", min_value=0, step=100)
avg_wallet_balance = st.number_input("Average Monthly Wallet Balance (NGN)", min_value=0, step=100)
days_inactive = st.number_input("Days Since Last Transaction", min_value=0, step=1)

# When user clicks predict
if st.button("Predict Fraud"):
    # Make a dataframe from inputs
    X_new = pd.DataFrame([[amount, wallet_balance, avg_wallet_balance, days_inactive]],
                         columns=["amount_(ngn)", "wallet_balance_(ngn)",
                                  "avg_monthly_wallet_balance", "days_since_last_transaction"])

    # Prediction
    prediction = model.predict(X_new)[0]

    if prediction == 1:
        st.error("⚠️ Suspicious transaction detected (Possible Fraud)")
    else:
        st.success("✅ Transaction looks normal")